### ISSUE TITLE
log4j layouts should be supported

### ISSUE THREAD

**Issue by softprops** [Graylog2/syslog4j-graylog2#1]
according to log4j's docs if an appender returns falls for an appenders `#requiresLayout` method [layouts are always ignore](https://github.com/apache/log4j/blob/c5f4279081091e562c44bb753f6e52dc6be5fa52/src/main/java/org/apache/log4j/Appender.java#L123-L126). log4j's native syslog appenders supports [layouts](https://github.com/apache/log4j/blob/c5f4279081091e562c44bb753f6e52dc6be5fa52/src/main/java/org/apache/log4j/net/SyslogAppender.java#L261-L264) but this one [does not](https://github.com/Graylog2/syslog4j-graylog2/blob/master/src/main/java/org/graylog2/syslog4j/impl/log4j/Syslog4jAppenderSkeleton.java#L264-L266). Was there a reason for this?

**Comment by joschi** [comment]
Thanks for reporting this!

This project is primarily a generic syslog library according to [RFC 3164](http://tools.ietf.org/html/rfc3164) and [RFC 5424](https://tools.ietf.org/html/rfc5424). While it contains a syslog appender for [Apache log4j](https://logging.apache.org/log4j/1.2/) (inherited from the original syslog4j project we forked), we do not intend support that functionality and will probably remove that in the future.

**Comment by joschi** [comment]
There is another, better maintained fork of syslog4j at https://github.com/NessComputing/syslog4j, though. If you want to use the log4j functionality, I'd recommend taking a look at that project.

**Comment by softprops** [comment]
Thanks @joschi I worked around by extending and overriding requiresLayout to return true
