### ISSUE TITLE
Priority 

### ISSUE THREAD

**Issue by Booyaabes** [Graylog2/syslog4j-graylog2#10]
Hi,

It seems that priority computed in _appendPriority_ (AbstractSyslogMessageProcessor.java line 68:` int priority = facility | level;`) is not compliant with RFC 3164 (https://tools.ietf.org/html/rfc3164):
_"The Priority value is calculated by first multiplying the Facility number by 8 and then adding the numerical value of the Severity"_
He is intended? Or maybe i'm missing something...

I didn't find a bug tracker to the original syslog4j project and i don't know if the original project is still active, so I decide to post here.

**Comment by joschi** [comment]
@Booyaabes Do you have specific problems with syslog4j generating wrong priority values or is it just a guess?

In general, the focus of this fork is mostly just the syslog parser and not the syslog server components of syslog4j.

You might have more success with either the original project at https://github.com/syslog4j/syslog4j or the fork at https://github.com/NessComputing/syslog4j

**Comment by Booyaabes** [comment]
Thx for your answer.
I have troubles sending syslog message to a little node.js application. I thought first that the problem comes from the node.js syslogd module that i used, but after analysing the problem with Wireshark, I realize that it comes from syslog4j, confirmed by syslog4j code source. I tried lots of forks. I posted here, as it's the only repository that seems still active. I'll open an issue in NessComputing and syslog4j asap.

**Comment by joschi** [comment]
@Booyaabes While it might seem non-obvious, the internal methods you've mentioned expect you to use the `SyslogConstants` class, which already contain constants for the correct facility values.

See [`UnixSyslogTest`](https://github.com/Graylog2/syslog4j-graylog2/blob/c5a5ae99381c66ec42f3a1cb5c7191e809452353/src/test/java/org/graylog2/syslog4j/impl/unix/UnixSyslogTest.java) and [`AbstractSyslogMessageProcessorTest`](https://github.com/Graylog2/syslog4j-graylog2/blob/c5a5ae99381c66ec42f3a1cb5c7191e809452353/src/test/java/org/graylog2/syslog4j/impl/message/processor/AbstractSyslogMessageProcessorTest.java) for examples.

**Comment by Booyaabes** [comment]
@joschi Thanks for your answer.
