### ISSUE TITLE
Its API javadoc?

### ISSUE THREAD

**Issue by xiaoleihuang** [Graylog2/syslog4j-graylog2#11]
Is the api doc the same as [syslog4j's java doc](http://www.syslog4j.org/docs/javadoc/)? Where is its api do Thank you.

**Comment by joschi** [comment]
@xiaoleihuang Yes, you can simply use the Javadocs of the original syslog4j project.

Alternatively you can fetch the Javadoc artifact from Maven Central (https://search.maven.org/remotecontent?filepath=org/graylog2/syslog4j/0.9.55/syslog4j-0.9.55-javadoc.jar) or view it on javadoc.io at https://www.javadoc.io/doc/org.graylog2/syslog4j/0.9.55

**Comment by xiaoleihuang** [comment]
Got it. Thank you.
