### ISSUE TITLE
Not all Syslog FACILITY levels can be specified

### ISSUE THREAD

**Issue by dfch** [Graylog2/syslog4j-graylog2#2]
[SyslogConstants.java](https://github.com/Graylog2/syslog4j-graylog2/blob/24daa908bcf37bda0e6487d9b5e2ed25a62323e8/src/main/java/org/graylog2/syslog4j/SyslogConstants.java):

The following Facility level constants are missing and therefore cannot be specified:

          12             NTP subsystem
          13             log audit (note 1)
          14             log alert (note 1)
          15             clock daemon (note 2)

See [RFC3164, 4.1.1 PRI Part](https://tools.ietf.org/html/rfc3164#section-4.1.1). This means that currently not all facility levels can be specified for sending a message.

**Comment by dfch** [comment]
hi guys, are there any plans on addressing this issue? 
you seem to have forked [syslog4j](http://syslog4j.org/) where the original comes from (but you are not comitting to it). Is there a means that I can contribute to your repo to fix this issue?

**Comment by dennisoelkers** [comment]
Sure, go ahead and submit a PR! :)

**Comment by joschi** [comment]
> you seem to have forked syslog4j where the original comes from (but you are not comitting to it).

Unfortunately the original project seems to be abandoned and not maintained anymore. There's another (more better maintained) fork at https://github.com/NessComputing/syslog4j but if you'd like to contribute to this library (which is being used in Graylog), just create issues or PRs in this repo.

**Comment by dfch** [comment]
@joschi you are referencing [NessComputing/syslog4j](https://github.com/NessComputing/syslog4j). So does it mean, that you will not maintain your (Graylog syslog4j) repo either and recommend to use the other?

**Comment by joschi** [comment]
@dfch No, not at all. I just wanted to emphasize that this repository is being used in Graylog and being catered towards the needs of that project and just if you were looking for a more generic usable syslog library you should consider using NessComputing/syslog4j. Sorry if that wasn't clear from my last reply.
