### ISSUE TITLE
the StringIndexOutOfBoundsException of SyslogServerEvent caused by empty byte[] can cause DatagramSocket does not work any more

### ISSUE THREAD

**Issue by pingpangkuangmo** [Graylog2/syslog4j-graylog2#5]
When client send empty byte[] to UDPNetSyslogServer, create a  SyslogServerEvent, now parse error,generate a StringIndexOutOfBoundsException,but not captured,so the run method of UDPNetSyslogServer over,does not work any more.

This bug also exists the original source code of Syslog4j,only exists in UDPNetSyslogServer,not in TCPNetSyslogServer.

This bug can be very simple resolved,in UDPNetSyslogServer just judge that the length of receiveData is greater than 0.if Less than or equal to 0,just ignore.

**Comment by joschi** [comment]
@pingpangkuangmo Thanks for reporting this!
